export const DragDropActionTypes = {
  DRAG_DROP_DRAGGING: 'DRAG_DROP_DRAGGING',
  DRAG_DRAG_ID: 'DRAG_DRAG_ID',
  DRAG_DROP_ID: 'DRAG_DROP_ID',
  DRAG_DROP_COORDS: 'DRAG_DROP_COORDS',
  DRAG_DROP_CLEAR: 'DRAG_DROP_CLEAR',
};
